### PR TITLE
CA-176: Add Docker based sandbox tools and revise docs.

### PR DESCRIPTION
**Pull request by grugnog**

### CODE REVIEW

**Comment by grugnog** [comment]
@alexiscott ahh - you must have a pretty old Docker install - target uses multi-stage builds which are in 17.05 and later (which is more than a year old). I added a check for this (and also the Jazz URL) in the activate script to give more helpful error messages!
If you can upgrade your Docker and retest I think it should work. I recommend using the instructions on https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository for Docker on Ubuntu. It would be helpful to have someone test on OS X also!

**Comment by acabouet** [comment]
Working when tested on Mac OS X. Okay to merge?

**Comment by alexiscott** [comment]
@grugnog thanks for the upgrade instructions link for docker. That got em further on Ubuntu.

I also tested on a MAC with latest docker for mac, stable:

On Mac with latest docker stable.

```
$ gatsby develop
error There was a problem loading the local develop command. Gatsby may not be installed. Perhaps you need to run "npm install"?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  civicactions.com git:(grugnog-docs) npm install
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
```

Ran npm i


```
⠁ { path: '/dev-404-page/',
  id: 'SitePage /dev-404-page/',
  parent: 'SOURCE',
  children: [],
  internal:
   { type: 'SitePage',
     contentDigest: 'f91d29e10ba680b413138cf9ed86e655',
     owner: 'internal-data-bridge',
     fieldOwners: { slug: 'default-site-plugin' } },
  fields: { slug: '/dev-404-page/' } }
error Plugin gatsby-source-jazz returned an error

```
cat .env
  TypeError: Parameter "url" must be a string, not undefined
GATSBY_JAZZ_URL=urlvalue

Updated .env value and renamed file:
mv .env .env.development

Site was then built on local server with yarn run develop

**Comment by grugnog** [comment]
@alexiscott I am looking at your suggestions and not sure I am following. The activate script runs `yarn install` for you, so that should not be necessary - we are not using the `npm` command at all on this project that I know of (it's not even wired up to run in the docker container).
Also, the instructions don't reference running `yarn gatsby` - do you mean we `yarn develop` (which we should replace with `yarn run develop`, which I can do)?
I don't think it should be necessary to have an .env.development file any more (and in my testing it is not) - we pass GATSBY_JAZZ_URL in as an environment variable. Are you sure you had sourced activate when testing this?

**Comment by alexiscott** [comment]
@grugnog 
Perhaps "yarn install" had not run, Gatsby may not be installed - being an indicator - hence my attempt to fudge with `npm install`.
Yes, yarn run develop
`. bin/activate`was the first thing I was doing.

**Comment by grugnog** [comment]
@alexiscott do you think you could try again and record the output of activate to see what happened when it ran yarn install? I might add some additional error checking to that script also.

**Comment by alexiscott** [comment]
Hi @grugnog 
Testing on MAC.
ZSH/ and Bash

The script does not seem to get beyond:
alex@Homer ~/workspace/CA/civicactions.com (grugnog-docs) $ . bin/activate
ERROR: Please set your Jazz API URL using `echo GATSBY_JAZZ_URL=urlvalue >> .env`

It never gets as far as yarn install --pure-lockfile

**Comment by alexiscott** [comment]
@grugnog let me know if it would be helpful for me to attempt debugging the script on my system in one way or another?

**Comment by grugnog** [comment]
@alexiscott Could you try this any report the results (removing the apikey value, for security)?
```
$ cat .env 
GATSBY_JAZZ_URL=https://api.resumatorapi.com/v1/jobs/status/open?apikey=KEYVALUE
$ source .env 
$ echo $GATSBY_JAZZ_URL 
https://api.resumatorapi.com/v1/jobs/status/open?apikey=KEYVALUE
```

**Comment by alexiscott** [comment]
~~~~
➜ . bin/activate
➜  grugnog-docs git:(docs) ✗  (grugnog-docs) $ cat .env
➜ cat: .env: No such file or directory
➜ echo GATSBY_JAZZ_URL=https://api.resumatorapi.com/v1/jobs/status/open\?apikey\=KEYVALUE >> .env
~~~~

~~~~
$ cat .env 
GATSBY_JAZZ_URL=https://api.resumatorapi.com/v1/jobs/status/open?apikey=KEYVALUE
$ source .env 
$ echo $GATSBY_JAZZ_URL 
https://api.resumatorapi.com/v1/jobs/status/open?apikey=KEYVALUE
➜ echo GATSBY_JAZZ_URL=https://api.resumatorapi.com/v1/jobs/status/open\?apikey\=KEYVALUE >> .env
~~~~

~~~~
echo $GATSBY_JAZZ_URL
https://api.resumatorapi.com/v1/jobs/status/open?apikey=KEYVALUE
➜  grugnog-docs git:(docs) ✗ . bin/activate
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
(standard_in) 1: parse error
Building home-sandbox container image
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Adding aliases for CLI tools: gatsby yarn node

Installing NPM packages with yarn
yarn install v1.2.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "ajv-errors@1.0.0" has unmet peer dependency "ajv@>=5.0.0".
warning "sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning "react-sizeme@2.5.2" has unmet peer dependency "prop-types@^15.0.0-0".
[4/4] 📃  Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.9.4" while you're on "1.2.1".
info To upgrade, run the following command:
$ curl -o- -L https://yarnpkg.com/install.sh | bash
✨  Done in 21.72s.

Activated - to get started run 'yarn develop', then go to http://localhost:8000/

~~~~

Then ran `yarn develop`

~~~~
➜  grugnog-docs git:(docs) ✗  (grugnog-docs) $ yarn develop
yarn run v1.2.1
$ gatsby develop
success open and validate gatsby-config — 0.011 s
success load plugins — 0.265 s
success onPreInit — 0.954 s
success delete html and css files from previous builds — 0.006 s
success initialize cache — 0.007 s
success copy gatsby files — 0.040 s
success onPreBootstrap — 0.005 s
⠁ { path: '/dev-404-page/',
  id: 'SitePage /dev-404-page/',
  parent: 'SOURCE',
  children: [],
  internal:
   { type: 'SitePage',
     contentDigest: 'f91d29e10ba680b413138cf9ed86e655',
     owner: 'internal-data-bridge',
     fieldOwners: { slug: 'default-site-plugin' } },
  fields: { slug: '/dev-404-page/' } }
error Plugin gatsby-source-jazz returned an error


  TypeError: Parameter "url" must be a string, not undefined

  - http.js:57 dispatchHttpRequest
    [grugnog-docs]/[axios]/lib/adapters/http.js:57:22

  - debuggability.js:303 Promise._execute
    [grugnog-docs]/[bluebird]/js/release/debuggability.js:303:9

  - promise.js:483 Promise._resolveFromExecutor
    [grugnog-docs]/[bluebird]/js/release/promise.js:483:18

  - promise.js:79 new Promise
    [grugnog-docs]/[bluebird]/js/release/promise.js:79:10

  - http.js:18 httpAdapter
    [grugnog-docs]/[axios]/lib/adapters/http.js:18:10

  - dispatchRequest.js:59 dispatchRequest
    [grugnog-docs]/[axios]/lib/core/dispatchRequest.js:59:10

  - util.js:16 tryCatcher
    [grugnog-docs]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [grugnog-docs]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [grugnog-docs]/[bluebird]/js/release/promise.js:569:18

  - promise.js:606 Promise._settlePromiseCtx
    [grugnog-docs]/[bluebird]/js/release/promise.js:606:10

  - async.js:138 Async._drainQueue
    [grugnog-docs]/[bluebird]/js/release/async.js:138:12

  - async.js:143 Async._drainQueues
    [grugnog-docs]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues
    [grugnog-docs]/[bluebird]/js/release/async.js:17:14


error Cannot read property 'filter' of undefined


  TypeError: Cannot read property 'filter' of undefined

  - api-runner-node.js:274 Promise.mapSeries.catch.then.results
    [grugnog-docs]/[gatsby]/dist/utils/api-runner-node.js:274:42

  - util.js:16 tryCatcher
    [grugnog-docs]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [grugnog-docs]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [grugnog-docs]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [grugnog-docs]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [grugnog-docs]/[bluebird]/js/release/promise.js:693:18

  - async.js:133 Async._drainQueue
    [grugnog-docs]/[bluebird]/js/release/async.js:133:16

  - async.js:143 Async._drainQueues
    [grugnog-docs]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues
    [grugnog-docs]/[bluebird]/js/release/async.js:17:14


error UNHANDLED REJECTION


  TypeError: Cannot read property 'filter' of undefined

  - api-runner-node.js:274 Promise.mapSeries.catch.then.results
    [grugnog-docs]/[gatsby]/dist/utils/api-runner-node.js:274:42

  - util.js:16 tryCatcher
    [grugnog-docs]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [grugnog-docs]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [grugnog-docs]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [grugnog-docs]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [grugnog-docs]/[bluebird]/js/release/promise.js:693:18

  - async.js:133 Async._drainQueue
    [grugnog-docs]/[bluebird]/js/release/async.js:133:16

  - async.js:143 Async._drainQueues
    [grugnog-docs]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues
    [grugnog-docs]/[bluebird]/js/release/async.js:17:14


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

~~~~

Updated GATSBY_JAZZ_URL to include the correct API keys then ran yarn develop:

~~~~

Server started up without errors at http://localhost:8000/

**Pull request merged**
