### PR TITLE
CA-379: gatsby jazz url optional

### PR DESCRIPTION
**Pull request by alexiscott**

### CODE REVIEW

**Comment by iris-i** [comment]
@alexiscott 
The concept of creating a placeholder/dummy Job page if the Jazz API url is not set sounds good to me.
I have a question that should probably go to @grugnog, is there any possibility that the live site will not have the Jazz API URL set? I'm wondering if we need to retain the check to ensure that the build fails if there's no url so we don't accidentally push the dummy job page to the live site.

**Comment by grugnog** [comment]
That's a good idea - maybe if it is set to "dev" we use the dummy page but still fail if it is blank?

**Comment by alexiscott** [comment]
@grugnog something like this?
```
// If environment variable is set to 'development':
  if (process.env.GATSBY_JAZZ_URL === 'development') {
```
....

**Comment by alexiscott** [comment]
@grugnog @iris-i  
Let me know if you think it works, now? We would just need to update the documentation, or add back that Docker file message about adding the Gatsby Jazz URL environment variable set to “development” to the .env file, for sandboxes.

**Comment by grugnog** [comment]
Looks good - rolled this into #596

**Pull request closed without merging**
